name: Create Json
#test test test test test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - uses: actions/checkout@master
#      with:
#        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
#        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Generate JSON
      uses: gtri/lowendinsight@gha
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
